### ISSUE TITLE
Using /kill makes you unable to take damage

### ISSUE THREAD

**Issue by KydZombie** [AnodeCathode/TNFC_Mod#13]
If you use /kill on a player, they are unable to die by any means, including mobs, fall damage, hunger, etc.
Restarting the world does not fix the issue, meaning you likely have to load a backup to continue playing
Seems to be caused by `[13:43:44] [Server thread/WARN] [firstaid]: New current health is not a number, setting it to 0!`
[latest.log](https://github.com/AnodeCathode/TNFC_Mod/files/8459604/latest.log)

**Comment by Gaelmare** [comment]
NBTEdit on the player's .dat file will fix this without resorting to backups. This issue is in tips and book. There's an issue with the firstaid mod, obviously.

**Comment by Gaelmare** [comment]
Unfortunately, this issue has no fix that we're aware of. The workarounds are to not use /kill, and NBT edit the player to fix if it's already occurred.
