### ISSUE TITLE
Garden Cloche Crop Growth

### ISSUE THREAD

**Issue by addis2123** [AnodeCathode/TNFC_Mod#6]
The Garden Cloche can not be provided enough power to grow TFC crops. When growth is halted due to low power the crop resets the growth cycle. I used the HV cables and a creative capacitor.

**Comment by AnodeCathode** [comment]
Well others are using them so I suspect something is wrong with your setup

**Comment by addis2123** [comment]
Possible, I'll see if I can get it to work better on a fresh install and world.

**Comment by AnodeCathode** [comment]
Fixed this at some point. Slight drop in Cloche power use
