### ISSUE TITLE
IE Assembler not working

### ISSUE THREAD

**Issue by JayDo96** [AnodeCathode/TNFC_Mod#7]
Is the Assembler disabled or is it broken atm? It doesnt craft any thing but it does us 1IF per tick

EDIT: it seems the issue is with using hammers in the recipes. It causes a crash in single player  but does nothing in multiplayer.

**Comment by AnodeCathode** [comment]
It's pretty broken. Atm may just be the way it is. IE 1.12.2 doesn't get fixed and I'm unlikely to fork it to fix that

**Comment by JayDo96** [comment]
Fair enough, do you know of a way to auto craft nuggets into scrap? The engineers workbench wont work either as it consumes the whole hammer per craft. Maybe we could use the metal press with steel block to crush nuggets into scrap.

**Comment by AnodeCathode** [comment]
Not too concerned about turning nuggets to scrap.
